### ISSUE TITLE
Sitemap is not live when it's pinged to the services

### ISSUE THREAD

**Issue by davidsneighbour** [cdeleeuwe/netlify-plugin-submit-sitemap#14]
In my output the ping to google/yandex/etc. is done before the site is put live. Because there is post processing involved the resulting site is "live" 6 minutes after the ping which in some cases is also after the Bots react to the ping. 

Is there any way to configure a sleep period or set the plugin to run after the "live" mark? We are submitting the link to the resulting sitemap, not the sitemap content itself?

**Comment by cdeleeuwe** [comment]
@davidsneighbour Yes correct, the plugin is only submitting the URL of the sitemap, not the sitemap itself.

Agree, it would be better to ping the services after it has been fully deployed. AFAIK, previously this wasn't possible with the current Netlify build events, but I think they are currently reworking the onSuccess event which should then trigger after deploy (instead of after build, but before deploy). Not sure if this is already live, or still WIP. See related issue https://github.com/netlify/plugins/issues/140

**Comment by cdeleeuwe** [comment]
Closing this because the new onSuccess behavior is already in production.
